//! Builds the Vue single page app and bakes its `dist/` output into the library.
//!
//! The generated `web_assets.rs` contains one `include_bytes!` entry per file, so the
//! whole web UI ends up inside `libmarkdown_core.a` and no files are shipped alongside it.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let ui_dir = manifest_dir
        .join("../../vue-project")
        .canonicalize()
        .expect("vue-project directory not found");
    let dist_dir = ui_dir.join("dist");

    for watched in [
        "src",
        "public",
        "index.html",
        "vite.config.ts",
        "package.json",
        "tsconfig.app.json",
    ] {
        println!("cargo:rerun-if-changed={}", ui_dir.join(watched).display());
    }
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=MARKDOWN_SKIP_UI_BUILD");

    if env::var("MARKDOWN_SKIP_UI_BUILD").as_deref() == Ok("1") {
        println!("cargo:warning=MARKDOWN_SKIP_UI_BUILD=1, reusing existing vue-project/dist");
    } else {
        build_ui(&ui_dir);
    }

    if !dist_dir.join("index.html").is_file() {
        panic!(
            "vue-project build produced no dist/index.html at {}",
            dist_dir.display()
        );
    }

    let mut files = BTreeMap::new();
    collect(&dist_dir, &dist_dir, &mut files);

    let mut generated = String::from(
        "// @generated by build.rs - do not edit.\npub static WEB_ASSETS: &[WebAsset] = &[\n",
    );
    for (route, path) in &files {
        generated.push_str(&format!(
            "    WebAsset {{ path: {route:?}, mime: {mime:?}, bytes: include_bytes!({path:?}) }},\n",
            mime = format!("{}\0", mime_for(route)),
            path = path.to_str().expect("non UTF-8 asset path"),
        ));
    }
    generated.push_str("];\n");

    let out = PathBuf::from(env::var("OUT_DIR").unwrap()).join("web_assets.rs");
    fs::write(&out, generated).expect("failed to write web_assets.rs");
}

fn build_ui(ui_dir: &Path) {
    let (program, install_args): (&str, &[&str]) = if which("bun") {
        ("bun", &["install", "--frozen-lockfile"])
    } else {
        ("npm", &["install"])
    };

    if needs_install(ui_dir) {
        run(ui_dir, program, install_args);
    }
    // `build-only` skips vue-tsc: type checking stays a separate, developer facing step.
    run(ui_dir, program, &["run", "build-only"]);
}

fn needs_install(ui_dir: &Path) -> bool {
    let bin = ui_dir.join("node_modules").join(".bin");
    if !bin.is_dir() {
        return true;
    }
    // A `node_modules` tree installed on another platform has no Windows shims,
    // so the local package binaries would not be runnable.
    cfg!(windows)
        && !fs::read_dir(&bin)
            .map(|entries| {
                entries.flatten().any(|e| {
                    e.path()
                        .extension()
                        .is_some_and(|ext| ext.eq_ignore_ascii_case("cmd"))
                })
            })
            .unwrap_or(true)
}

fn which(program: &str) -> bool {
    command(program)
        .arg("--version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

// On Windows `npm`/`bun` are `.cmd` shims, which `Command::new` does not resolve,
// so they have to be launched through the command interpreter.
fn command(program: &str) -> Command {
    if cfg!(windows) {
        let mut cmd = Command::new("cmd");
        cmd.arg("/C").arg(program);
        cmd
    } else {
        Command::new(program)
    }
}

// `cmd` does not understand the `\\?\` extended-length prefix, so strip it.
#[cfg(windows)]
fn display_path(dir: &Path) -> String {
    let path = dir.display().to_string();
    match path.strip_prefix(r"\\?\UNC\") {
        Some(rest) => format!(r"\\{rest}"),
        None => path.strip_prefix(r"\\?\").unwrap_or(&path).to_string(),
    }
}

fn run(dir: &Path, program: &str, args: &[&str]) {
    println!("cargo:warning=running `{program} {}`", args.join(" "));
    let status = spawn(dir, program, args)
        .unwrap_or_else(|e| panic!("failed to spawn `{program}`: {e}"));
    assert!(status.success(), "`{program} {}` failed", args.join(" "));
}

// `pushd` maps a UNC directory to a temporary drive letter, which `cmd`
// requires because it cannot use a UNC path as the current directory.
#[cfg(windows)]
fn spawn(dir: &Path, program: &str, args: &[&str]) -> std::io::Result<std::process::ExitStatus> {
    use std::os::windows::process::CommandExt;
    Command::new("cmd")
        .arg("/C")
        .raw_arg(format!(
            "\"pushd \"{}\" && {program} {}\"",
            display_path(dir),
            args.join(" ")
        ))
        .status()
}

#[cfg(not(windows))]
fn spawn(dir: &Path, program: &str, args: &[&str]) -> std::io::Result<std::process::ExitStatus> {
    Command::new(program).args(args).current_dir(dir).status()
}

fn collect(root: &Path, dir: &Path, out: &mut BTreeMap<String, PathBuf>) {
    for entry in fs::read_dir(dir).expect("failed to read dist directory") {
        let path = entry.expect("failed to read dist entry").path();
        if path.is_dir() {
            collect(root, &path, out);
        } else {
            let route = path
                .strip_prefix(root)
                .expect("asset outside dist")
                .to_str()
                .expect("non UTF-8 asset path")
                .replace('\\', "/");
            out.insert(route, path);
        }
    }
}

fn mime_for(path: &str) -> &'static str {
    match path.rsplit('.').next().unwrap_or_default() {
        "html" => "text/html; charset=utf-8",
        "js" | "mjs" => "text/javascript; charset=utf-8",
        "css" => "text/css; charset=utf-8",
        "json" | "map" => "application/json; charset=utf-8",
        "svg" => "image/svg+xml",
        "png" => "image/png",
        "jpg" | "jpeg" => "image/jpeg",
        "gif" => "image/gif",
        "webp" => "image/webp",
        "avif" => "image/avif",
        "ico" => "image/vnd.microsoft.icon",
        "woff" => "font/woff",
        "woff2" => "font/woff2",
        "ttf" => "font/ttf",
        "otf" => "font/otf",
        "wasm" => "application/wasm",
        "txt" => "text/plain; charset=utf-8",
        _ => "application/octet-stream",
    }
}
